# Generated by Django 4.1.3 on 2022-11-01 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_bookdata_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookdata',
            name='rating',
            field=models.FloatField(),
        ),
    ]
